---
# BMC management (Bare metal power and bios controls)
:enabled: true
# Available providers:
# - freeipmi / ipmitool - requires the appropriate package installed, and the rubyipmi gem
# - shell - for local reboot control (requires sudo access to /sbin/shutdown for the proxy user)
:bmc_default_provider: ipmitool
