#
# puppet_proxy_pupppet_api module is used for puppet versions 4.0 and higher
#
# puppet_proxy_pupppet_api is configured automatcially based on
# :puppet_version setting in smart-proxy's puppet.yml configuration file.
#
---
# URL of the puppet master itself for API requests.
:puppet_url: https://puppet.moria.smartsheet.com:8140
#
# SSL certificates used to access the puppet API
:puppet_ssl_ca: /etc/puppetlabs/puppet/certchain.pem
:puppet_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/ss-puppet-0401.moria.smartsheet.com.pem
:puppet_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/ss-puppet-0401.moria.smartsheet.com.pem
